default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: polymathic-intranet_development

test:
  <<: *default
  database: polymathic-intranet_test
